export type ErrorCode =
  | "ID_INVALID"
  | "TIME_INVALID"
  | "END_BEFORE_START"
  | "DURATION_TOO_LONG"
  | "AMOUNT_INVALID"
  | "COMMISSION_INVALID"
  | "PAYMENT_INVALID"
  | "DATE_INVALID"
  | "ID_CONFLICT";
